---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.tacoRegistry.name }}
  namespace: {{ .Values.namespace }}
data:
  config.yml: |-
    version: 0.1
    log:
      level: debug
      formatter: text
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
      cache:
        blobdescriptor: inmenory
    auth:
      token:
        realm: http://{{ .Values.tacoRegistryApp.ingress.host }}:{{ .Values.ingressPort }}/api/oauth/token
        service: {{ .Values.tacoRegistry.deployment.auth.service }}
        issuer: {{ .Values.tacoRegistry.deployment.auth.issuer }}
        rootcertbundle: /ssl/server.crt
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    notifications:
      events:
        includereferences: true
      endpoints:
        - name: builder-listener
          disabled: false
          url: http://{{ .Values.tacoRegistryBuilder.name }}:4000/v1/listener
          timeout: 3s
          threshold: 10
          backoff: 1s
          ignoredmediatypes:
            - application/octet-stream
          ignore:
            mediatypes:
              - application/octet-stream
            actions:
              - pull
              - delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.tacoRegistry.name }}-ssl
  namespace: {{ .Values.namespace }}
data:
  server.crt: |-
    -----BEGIN CERTIFICATE-----
    MIICljCCAX4CCQCRVZw4rRv0hTANBgkqhkiG9w0BAQsFADANMQswCQYDVQQGEwJr
    cjAeFw0yMDA3MTQwODM2MzFaFw00NzExMjkwODM2MzFaMA0xCzAJBgNVBAYTAmty
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1upYzB72PshCKevSbMWC
    l/NtBjSXp+YfDwST8ovNJ0Jsr5w9BFVLdxlCfj8DvxTZLtbWSpRf4PGB2Pq70l8o
    kE2gZCQ6Qo3UNt3AU1eUV4DUeNWQ5a8rZt9kAIIdbxqnIFJbfbuCbGd4TEEiKjrA
    eEXcVd2Ln06oTwDkc9wrICX5V4wPLJgvGJDzl+gC+Pc39E52LeL+q7/41clhIxPe
    wHk8MsIz2Cda1DcJQKDfve/a0J7H7kcdlGVDyBLBClCCMnFFSFzlYaNiM4l79kMr
    eX3mOjezjMNxOeqlhoBfw4vQiNCjzBp2ek1fKU6cr0cDkO0Ikww9L2DpolTYMdiK
    QQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQC8PbQFbzBSZFHz6JGc9ZFkPJWpJ/wy
    4GFV1esHkzk6zCJxRO51FxDd5z7RQum0OC+vgSLODxoZXzqc4pJYU9JfqIzbNLO9
    +lzLqhdr2Wdj360hcH3jbZA6IjOIXHXKBtFLw6wLUULk6RZxs0kRkWupyq9ywkSN
    03bYmo1pMhcBA09J/1DOAzyfrlNUvImIHoGWuqJMYtH37YkgX1jGN23o8xRbhQwe
    Q0dHXF+S/RSxKScrKPLpkmX8HzQtMC9jc1C+pWsfWjsQC9reHMe8bByAY3ihmYcH
    g0fZI3/I8A2930dKcKGHmz85O2eeUB8OWe2CLs4YDb5g8/KSNSEGn0vc
    -----END CERTIFICATE-----