apiVersion: {{ .Values.apiVersion.infrastructure }}
kind: AWSCluster
metadata:
  name: {{ .Values.cluster.name }}
spec:
  region: {{ .Values.cluster.region }}
  sshKeyName: {{ .Values.sshKeyName }}
  {{- with .Values.cluster.networkSpec }}
  networkSpec:
    {{- toYaml . | nindent 4 }}
  {{- end }}