apiVersion: {{ .Values.apiVersion.infrastructure }}
kind: AWSCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  region: {{ .Values.cluster.region }}
  sshKeyName: {{ .Values.sshKeyName }}
  {{- with .Values.cluster.networkSpec }}
  networkSpec:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cluster.bastion }}
  bastion:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.cluster.baseOS }}
  imageLookupBaseOS: {{ .Values.cluster.baseOS }}
  {{- end }}
