apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.machinePool }}
  clusterNetwork:
    pods:
      cidrBlocks: {{ .Values.cluster.podCidrBlocks }}
  {{- end }}
  infrastructureRef:
    apiVersion: {{ .Values.apiVersion.infrastructure }}
    kind: AWSCluster
    name: {{ .Values.cluster.name }}
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: {{ .Values.apiVersion.controlplane }}
    name: "{{ .Values.cluster.name }}-control-plane"