---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-api-aws.fullname" . }}
data:
  generate_machine_pool.py: |
{{ .Files.Get "artifacts/generate_machine_pool.py" | indent 4 }}

  wait_and_initialize.py: |
{{ .Files.Get "artifacts/wait_and_initialize.py" | indent 4 }}

  mp.raw.yaml: |
{{ tuple "mp/_mp.yaml" . | include "helper_template" | indent 4 }}

  argo-register.sh: |
{{ .Files.Get "artifacts/argo-register.sh" | indent 4 }}
