{{- if .Values.machineDeployment.enabled }}
apiVersion: {{ .Values.apiVersion.bootstrap }}
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Values.cluster.name }}-md-0
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: aws
          name: '{{`{{ ds.meta_data.local_hostname }}`}}'
{{- end }}
