apiVersion: {{ .Values.apiVersion.bootstrap }}
kind: KubeadmConfig
metadata:
  name: {{ .Values.cluster.name }}-mp-0
  namespace: {{ .Release.Namespace }}
spec:
  joinConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: aws
      name: '{{`{{ ds.meta_data.local_hostname }}`}}'