---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tacoRegistry.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.tacoRegistry.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.tacoRegistry.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tacoRegistry.name }}
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.tacoRegistry.name }}-data
        - name: config
          configMap:
            name: {{ .Values.tacoRegistry.name }}
      containers:
      - name: {{ .Values.tacoRegistry.name }}
        image: {{ .Values.tacoRegistry.deployment.image }}
        imagePullPolicy: Always
        volumeMounts:
          - name: data
            mountPath: /var/lib/registry
          - name: config
            mountPath: /etc/docker/registry
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tacoRegistry.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.tacoRegistry.name }}
spec:
  type: {{ .Values.tacoRegistry.service.type }}
  ports:
    {{- range .Values.tacoRegistry.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- end }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end}}
  selector:
    app: {{ .Values.tacoRegistry.name }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.tacoRegistry.name }}-1
  namespace: {{ .Release.Namespace }}
  {{- with .Values.tacoRegistry.ingress1.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.tacoRegistry.ingress1.host }}
      http:
        paths:
        {{- $root := . -}}
        {{- range .Values.tacoRegistry.ingress1.paths }}
        - path: {{ .path }}
          backend:
            serviceName: {{ $root.Values.tacoRegistry.name }}
            servicePort: {{ .port }}
        {{- end }}
{{ if .Values.tacoRegistry.ingress2.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.tacoRegistry.name }}-2
  namespace: {{ .Release.Namespace }}
  {{- with .Values.tacoRegistry.ingress2.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.tacoRegistry.ingress2.host }}
      http:
        paths:
        {{- $root := . -}}
        {{- range .Values.tacoRegistry.ingress2.paths }}
        - path: {{ .path }}
          backend:
            serviceName: {{ $root.Values.tacoRegistry.name }}
            servicePort: {{ .port }}
        {{- end }}
{{- end }}
{{ if .Values.tacoRegistry.ingressPub1.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.tacoRegistry.name }}-pub-1
  namespace: {{ .Release.Namespace }}
  {{- with .Values.tacoRegistry.ingressPub1.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.tacoRegistry.ingressPub1.host }}
      http:
        paths:
        {{- $root := . -}}
        {{- range .Values.tacoRegistry.ingressPub1.paths }}
        - path: {{ .path }}
          backend:
            serviceName: {{ $root.Values.tacoRegistry.name }}
            servicePort: {{ .port }}
        {{- end }}
{{- end}}
{{ if .Values.tacoRegistry.ingressPub2.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.tacoRegistry.name }}-pub-2
  namespace: {{ .Release.Namespace }}
  {{- with .Values.tacoRegistry.ingressPub2.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.tacoRegistry.ingressPub2.host }}
      http:
        paths:
        {{- $root := . -}}
        {{- range .Values.tacoRegistry.ingressPub2.paths }}
        - path: {{ .path }}
          backend:
            serviceName: {{ $root.Values.tacoRegistry.name }}
            servicePort: {{ .port }}
        {{- end }}
{{- end}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.tacoRegistry.name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.tacoRegistry.volume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tacoRegistry.volume.data.size }}
