---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tacoRegistry.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.tacoRegistry.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.tacoRegistry.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tacoRegistry.name }}
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.tacoRegistry.name }}-data
        - name: config
          configMap:
            name: {{ .Values.tacoRegistry.name }}
      containers:
      - name: {{ .Values.tacoRegistry.name }}
        image: {{ .Values.tacoRegistry.deployment.image }}
        imagePullPolicy: Always
        volumeMounts:
          - name: data
            mountPath: /var/lib/registry
          - name: config
            mountPath: /etc/docker/registry
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tacoRegistry.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.tacoRegistry.name }}
spec:
  type: {{ .Values.tacoRegistry.service.type }}
  ports:
    {{- range .Values.tacoRegistry.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- end }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end}}
  selector:
    app: {{ .Values.tacoRegistry.name }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.tacoRegistry.name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.tacoRegistry.volume.storageClassName }}
  accessModes:
    - {{ .Values.tacoRegistry.volume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.tacoRegistry.volume.data.size }}
