cluster:
  name: capi-quickstart
  region: ap-northeast-2
  sshKeyName: default
  networkSpec:
    vpc:
      # id: vpc-id
      # tags:
      #  string: string
      # cidrBlock: 10.0.0.0/16 
      availabilityZoneUsageLimit: 3 # default 3
  kubernetesVersion: v1.18.16
  podCidrBlocks:
  - 192.168.0.0/16

apiVersion:
  infrastructure: infrastructure.cluster.x-k8s.io/v1alpha3
  controlplane: controlplane.cluster.x-k8s.io/v1alpha3
  bootstrap: bootstrap.cluster.x-k8s.io/v1alpha3

kubeadmControlPlane:
  replicas: 3

aws:
  controlPlaneMachineType: t3.large
  workloadMachineType: t3.large
  sshKeyName: default
  availabilityZones:
  - ap-northeast-2

machinePool:
  enabled: true
  replicas: 3
  minSize: 1
  maxSize: 10
  subnets: []
  # - id: subnet-0c41662a89d7878a2
  # - id: subnet-03d16e2084d9f392b
  # - id: subnet-03ad0968f68bfa639

machineDeployment:
  replicas: 3
