{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

{{- $job := .Values.job }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $release_name }}"
  labels:
    helm.sh/chart: "{{ $chart_name }}-{{ $chart_version }}"
    app.kubernetes.io/name: "{{ $chart_name }}"
    app.kubernetes.io/instance: "{{ $release_name }}"
    app.kubernetes.io/version: "{{ $chart_version }}"
spec:
  schedule: {{ $job.schedule | quote }}
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            helm.sh/chart: "{{ $chart_name }}-{{ $chart_version }}"
            app.kubernetes.io/name: "{{ $chart_name }}"
            app.kubernetes.io/instance: "{{ $release_name }}"
            app.kubernetes.io/version: "{{ $chart_version }}"
        spec:
          containers:
          {{- $transfer := .Values.job.spec.containers.transfer }}
          - image: "{{ $transfer.image.repository }}:{{ $transfer.image.tag }}"
            imagePullPolicy: {{ $transfer.imagePullPolicy }}
            name: {{ $transfer.name }}
            command: {{ $transfer.command }}
            env:
            - name: BACKUP_SERVER_PASSWORD_PATH
              value: /app/.password
            volumeMounts:
            - name: shared-data
              mountPath: /app/cloudconsole
            - name: transfer-sh
              mountPath: /app/shell
            - name: password
              mountPath: /app/.password
              subPath: password
            - name: tz-config
              mountPath: /etc/localtime
          restartPolicy: {{ $job.spec.restartPolicy }}
          volumes:
          - name: shared-data
            emptyDir: {}
          - name: transfer-sh
            configMap:
              name: {{ $release_name }}-sh
              defaultMode: 0500
          - name: password
            secret:
              defaultMode: 0400
              secretName: {{ $release_name }}-secret
          - name: tz-config
            hostPath:
              path: /usr/share/zoneinfo/Asia/Seoul
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}

