{{- if and .Values.elasticsearchOperator.enabled .Values.elasticsearchOperator.createCustomResource }}
apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-operator-cleanup
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: {{ template "elasticsearch-operator.name" . }}-operator
{{ include "elasticsearch-operator.labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: {{ template "elasticsearch-operator.name" . }}-operator-cleanup
      labels:
        app: {{ template "elasticsearch-operator.name" . }}-operator
    spec:
    {{- if .Values.elasticsearchOperator.rbac.create }}
      serviceAccountName: elastic-operator-cleanup
    {{- end }}
      containers:
        - name: kubectl
          image: "{{ .Values.elasticsearchOperator.hyperkubeImage.repository }}:{{ .Values.elasticsearchOperator.hyperkubeImage.tag }}"
          imagePullPolicy: "{{ .Values.elasticsearchOperator.hyperkubeImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - >
              kubectl delete elasticsearch  --all;
              kubectl delete apmserver      --all;
              kubectl delete kibana         --all;
              sleep 10;

              kubectl delete crd apmservers.apm.k8s.elastic.co;
              kubectl delete crd elasticsearches.elasticsearch.k8s.elastic.co;
              kubectl delete crd kibanas.kibana.k8s.elastic.co;
      restartPolicy: OnFailure
{{- end }}

