{{- if .Values.elasticsearchOperator.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-operator
  namespace: {{ default .Release.Namespace .Values.elasticsearchOperator.namespace }}
  labels:
    control-plane: elastic-operator
spec:
  selector:
    matchLabels:
      control-plane: elastic-operator
  serviceName: elastic-operator
  template:
    metadata:
      labels:
        control-plane: elastic-operator
    spec:
      serviceAccountName: elastic-operator
      containers:
      - image: "{{ .Values.elasticsearchOperator.image.repository }}:{{ .Values.elasticsearchOperator.image.tag }}"
        name: elasticsearch-manager
        args: ["manager", "--operator-roles", "all", "--log-verbosity=0"]
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: WEBHOOK_SECRET
            value: elastic-webhook-server-cert
          - name: WEBHOOK_PODS_LABEL
            value: elastic-operator
          - name: OPERATOR_IMAGE
            value: "{{ .Values.elasticsearchOperator.image.repository }}:{{ .Values.elasticsearchOperator.image.tag }}"
        resources:
{{ toYaml .Values.elasticsearchOperator.resources | indent 10 }}
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: elastic-webhook-server-cert
{{- end }}
