apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taco-watcher.fullname" . }}
  labels:
{{ include "taco-watcher.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "taco-watcher.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "taco-watcher.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: watcher
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /home/tacomo/tacomo-webserver/conf/tacomo.conf
          subPath: tacomo.conf
        - name: sql
          mountPath: /home/tacomo/tacomo-webserver/sql/tacomodb_1.sql
          subPath: tacomodb_1.sql
        - name: db-volume
          mountPath: /home/tacomo/tacomo-webserver/dbdata
        - name: log-volume
          mountPath: /home/tacomo/tacomo-webserver/logs
      volumes:
      - name: conf
        configMap:
          name: {{ template "taco-watcher.fullname" . }}
          items:
          - key: tacomo.conf
            path: tacomo.conf
      - name: sql
        configMap:
          name: {{ template "taco-watcher.fullname" . }}
          items:
          - key: tacomodb_1.sql
            path: tacomodb_1.sql
      - name: db-volume
        persistentVolumeClaim:
          claimName: {{ template "taco-watcher.fullname" . }}-pvc
      - name: log-volume
        hostPath:
          path: /home/ubuntu
          type: Directory
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      resources:
         {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
