apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "taco-watcher.fullname" . }}-pvc
  labels:
    app: {{ template "taco-watcher.name" . }}
    chart: {{ template "taco-watcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.resources.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    limits: 
      storage: {{ .Values.resources.limits.storage }} 
    requests:
      storage: {{ .Values.resources.requests.storage }}
