apiVersion: v1
kind: Service
metadata:
  name: {{ include "taco-watcher.fullname" . }}
  labels:
{{ include "taco-watcher.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
{{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "taco-watcher.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
