destUser: taco
destPassword: npinfra1!
destHost: 10.12.1.99
destDir: ~/jenkins_bak/
containers:
  sshpass: 
    image:
      repository: pseudojo/docker-sshd-with-curl
      tag: alpine3.12
      imagePullPolicy: IfNotPresent
  k8s: 
    image:
      repository: alpine/k8s
      tag: 1.18.2
      imagePullPolicy: IfNotPresent
job:
  schedule: "32 18 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
