apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: {{ .Release.Namespace }}
data:
  metricsConfig: |
    disableLegacy: true
    enabled: true
    path: /metrics
    port: 9090
{{- if .Values.artifactRepository.enabled }}
  artifactRepository: |
    archiveLogs: true
{{- with .Values.artifactRepository.s3 }}
    s3:
{{ toYaml . | indent 6 }}
{{- end }}
{{- end }}

{{- if .Values.workflowArchive.enabled }}
  persistence: |
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
      connMaxLifetime: 0s
    nodeStatusOffLoad: true
    archive: true
    archiveTTL: {{ .Values.workflowArchive.archiveTTL }}
{{- with .Values.workflowArchive.mysql }}
    mysql:
{{ toYaml . | indent 6 }}
{{- end }}
{{- end }}
