{{- if .Values.mysql.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: argo-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      name: argo-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          value: {{ .Values.mysql.user }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.password }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        name: main
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - mysql
            - -u
            - {{ .Values.mysql.user }}
            - -p{{ .Values.mysql.password }}
            - {{ .Values.mysql.database }}
            - -e
            - SELECT 1
          initialDelaySeconds: 15
          timeoutSeconds: 2
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: argo-mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
{{- end }}
