{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: argo-mysql-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password:  {{ .Values.mysql.mysqlPassword | b64enc | quote }}
  username:  {{ .Values.mysql.mysqlUser | b64enc | quote }}
{{ end }}

