{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: argo-mysql-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password:  {{ .Values.mysql.password | b64enc | quote }}
  username:  {{ .Values.mysql.user | b64enc | quote }}
{{ end }}

