apiVersion: v1
kind: Service
metadata:
  name: argo-server
spec:
  ports:
  - name: web
    port: 2746
    targetPort: 2746
{{- if eq .Values.argoServer.service.type "NodePort" }}
    nodePort: {{ .Values.argoServer.service.nodePort }}
{{- end }}
  type: {{ .Values.argoServer.service.type }}
  selector:
    app: argo-server

