apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - {{ .Values.workflowController.executor.image.repository }}:{{ .Values.workflowController.executor.image.tag }}
        - --namespaced
        command:
        - workflow-controller
        image: {{ .Values.workflowController.image.repository }}:{{ .Values.workflowController.image.tag }}
        name: workflow-controller
      nodeSelector:
        kubernetes.io/os: linux
{{ toYaml .Values.nodeSelector | indent 8 }}
      serviceAccountName: argo
