apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - {{ .Values.workflowController.executor.image.repository }}:{{ .Values.workflowController.executor.image.tag }}
        - --namespaced
        command:
        - workflow-controller
        image: {{ .Values.workflowController.image.repository }}:{{ .Values.workflowController.image.tag }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 30
        name: workflow-controller
	    ports:
        - containerPort: 9090
          name: metrics
      nodeSelector:
        kubernetes.io/os: linux
{{- with .Values.nodeSelector }}
{{ toYaml . | indent 8 }}
{{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: argo
