{{- $sshpass := .Values.containers.sshpass }}
{{- $k8s := .Values.containers.k8s }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "cronjob-backup-jenkins"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "cronjob-backup-jenkins"
    app.kubernetes.io/instance: "cronjob-backup-jenkins"
spec:
  schedule: "{{ .Values.job.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: "cronjob-backup-jenkins"
            app.kubernetes.io/instance: "cronjob-backup-jenkins"
        spec:
          serviceAccount: backup-jenkins-sa
          containers:
          - image: "{{ $sshpass.image.repository }}:{{ $sshpass.image.tag }}"
            imagePullPolicy: {{ $sshpass.image.imagePullPolicy }}
            name: sshpass
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - name: scp-sh
                mountPath: /root/shell
              - name: ssh-secret
                mountPath: "/root/ssh"
                readOnly: true
          - image: "{{ $k8s.image.repository }}:{{ $k8s.image.tag }}"
            imagePullPolicy: {{ $k8s.image.imagePullPolicy }}
            name: k8s
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            command:
              - /root/shell/backup.sh
            volumeMounts:
              - name: backup-sh
                mountPath: /root/shell
          restartPolicy: Never
          volumes:
            - name: backup-sh
              configMap:
                name: backup-sh
                defaultMode: 0500
            - name: scp-sh
              configMap:
                name: scp-sh
                defaultMode: 0500
            - name: ssh-secret
              secret:
                secretName: ssh-secret
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
