apiVersion: v1
kind: Secret
metadata:
  name: argo-postgres-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgresql-password:  {{ .Values.postgres.password | b64enc | quote }}
  postgresql-username:  {{ .Values.postgres.username | b64enc | quote }}
