{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.istio.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-controlplane
  namespace: {{ .Release.Namespace  }}
  labels:
    monitoring: istio-dataplane
spec:
  jobLabel: istio
  selector:
    matchExpressions:
      - {key: istio, operator: In, values: [mixer,pilot,galley,citadel,sidecar-injector]}
  namespaceSelector:
    any: true
  endpoints:
  - port: http-monitoring
    {{- if .Values.serviceMonitor.istio.interval }}
    interval: {{ .Values.serviceMonitor.istio.interval }}
    {{- end }}
  - port: http-policy-monitoring
    {{- if .Values.serviceMonitor.istio.interval }}
    interval: {{ .Values.serviceMonitor.istio.interval }}
    {{- end }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-dataplane
  namespace: {{ .Release.Namespace  }}
  labels:
    monitoring: istio-dataplane
spec:
  selector:
    matchExpressions:
      - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats
  endpoints:
  - path: /stats/prometheus
    targetPort: http-envoy-prom
    {{- if .Values.serviceMonitor.istio.interval }}
    interval: {{ .Values.serviceMonitor.istio.interval }}
    {{- end }}
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
    - action: labelmap
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
{{- end }}
