{{- if .Values.customResource.elasticsearch.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ template "elasticsearch-operator.name" . }}-elasticsearch
spec:
  version: {{ .Values.customResource.elasticsearch.image.tag }}
  image: {{ .Values.customResource.elasticsearch.image.repository }}:{{ .Values.customResource.elasticsearch.image.tag }}
{{- if not .Values.customResource.elasticsearch.podDisruptionBudget.enabled }}
  podDisruptionBudget: {}
{{- end }}
  nodeSets:
{{- range $name, $node := .Values.customResource.elasticsearch.nodeSets}}
  {{- if $node.enabled}}
  - name: {{ $name}}
    count: {{ $node.count }}
    config:
  {{- toYaml $node.config | nindent 6 }}
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            limits:
              memory: {{ $node.limitMem | quote }}
              cpu: {{ $node.limitCpu }}   
          env:
          - name: ES_JAVA_OPTS
            value: {{ $node.javaOpts | quote }}
  {{- if $node.nodeSelector }}
        nodeSelector:
    {{- toYaml $node.nodeSelector | nindent 10 }}
  {{- end }}
  {{- if $node.pvc }}
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: {{ $node.pvc.size }}
          storageClassName: {{ $node.pvc.storageClassName }}
  {{- end }}
        # this changes the kernel setting on the node to allow ES to use mmap
        # if you uncomment this init container you will likely also want to remove the
        # "node.store.allow_mmap: false" setting above
        # initContainers:
        # - name: sysctl
        #   securityContext:
        #     privileged: true
        #   command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']

     
  {{- end}}  
{{- end}}  
  # - http:
  #   service:
  #     ports:
  #     - name: https
  #       nodePort: 30002
  #       port: 9200
  #       protocol: TCP
  #       targetPort: 9200        
  ## inject secure settings into Elasticsearch nodes from k8s secrets references
  # secureSettings:
  # - secretName: ref-to-secret
  # - secretName: another-ref-to-secret
  #   # expose only a subset of the secret keys (optional)
  #   entries:
  #   - key: value1
  #     path: newkey # project a key to a specific path (optional)
{{- if .Values.customResource.elasticsearch.http }}
{{ toYaml .Values.customResource.elasticsearch.http | indent 2 }}
{{- end }}
{{- end }}
