{{- if .Values.customResource.elasticsearch.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ template "elasticsearch-operator.name" . }}-elasticsearch
spec:
  version: {{ .Values.customResource.elasticsearch.image.tag }}
  image: {{ .Values.customResource.elasticsearch.image.repository }}:{{ .Values.customResource.elasticsearch.image.tag }}
{{- if not .Values.customResource.elasticsearch.podDisruptionBudget.enabled }}
  podDisruptionBudget: {}
{{- end }}
  nodeSets:
  - name: default
    count: {{ .Values.customResource.elasticsearch.count }}
    config:
{{ toYaml .Values.customResource.elasticsearch.config | indent 6 }}
{{- if .Values.customResource.elasticsearch.nodeSelector }}
    podTemplate:
      spec:
        nodeSelector:
{{ toYaml .Values.customResource.elasticsearch.nodeSelector | indent 10 }}
{{- end }}
{{- if .Values.customResource.elasticsearch.volumeClaimTemplates }}
    volumeClaimTemplates:
{{ toYaml .Values.customResource.elasticsearch.volumeClaimTemplates | indent 6 }}
{{- end }}
        # this changes the kernel setting on the node to allow ES to use mmap
        # if you uncomment this init container you will likely also want to remove the
        # "node.store.allow_mmap: false" setting above
        # initContainers:
        # - name: sysctl
        #   securityContext:
        #     privileged: true
        #   command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            limits:
              memory: 8Gi
              cpu: 2
          env:
          - name: ES_JAVA_OPTS
            value: {{ .Values.customResource.elasticsearch.javaOpts | quote }}
          resources:
            limits:
              memory: {{ .Values.customResource.elasticsearch.limitMem | quote }}
              cpu: {{ .Values.customResource.elasticsearch.limitCpu | quote }}          
  # - http:
  #   service:
  #     ports:
  #     - name: https
  #       nodePort: 30002
  #       port: 9200
  #       protocol: TCP
  #       targetPort: 9200        
  ## inject secure settings into Elasticsearch nodes from k8s secrets references
  # secureSettings:
  # - secretName: ref-to-secret
  # - secretName: another-ref-to-secret
  #   # expose only a subset of the secret keys (optional)
  #   entries:
  #   - key: value1
  #     path: newkey # project a key to a specific path (optional)
{{- if .Values.customResource.elasticsearch.http }}
{{ toYaml .Values.customResource.elasticsearch.http | indent 2 }}
{{- end }}
{{- end }}
