{{- if .Values.customResource.kibana.enabled }}
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: {{ template "elasticsearch-operator.name" . }}-kibana-dashboard
spec:
  version: {{ .Values.customResource.kibana.version }}
{{- if .Values.customResource.kibana.image }}
  image: {{ .Values.customResource.kibana.image }}:{{ .Values.customResource.kibana.version }}
{{- end }}
  count: 1
  elasticsearchRef:
    name: {{ template "elasticsearch-operator.name" . }}-elasticsearch
{{ toYaml .Values.customResource.kibana.http | indent 2 }}
  podTemplate:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
{{- end }}
