{{- if .Values.customResource.kibana.enabled }}
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: {{ template "elasticsearch-operator.name" . }}-kibana-dashboard
spec:
  version: {{ default "7.4.2" .Values.customResource.kibana.image.tag }}
  image: "{{ .Values.customResource.kibana.image.repository }}:{{ .Values.customResource.kibana.image.tag }}"
{{- if .Values.customResource.kibana.nodeSelector }}
  nodeSelector:
{{ toYaml .Values.customResource.kibana.nodeSelector | indent 4 }}
{{- end }}
  count: 1
  elasticsearchRef:
    name: {{ template "elasticsearch-operator.name" . }}-elasticsearch
{{- if .Values.customResource.kibana.http }}
  http:
{{ toYaml .Values.customResource.kibana.http | indent 4 }}
{{- end }}
  podTemplate:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: {{ .Values.customResource.kibana.limitMem | quote }}
            cpu: {{ .Values.customResource.kibana.limitCpu }}             
{{- if .Values.customResource.kibana.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.customResource.kibana.nodeSelector | indent 8 }}
{{- end }}
{{- end }}
