{{- if and .Values.customResource.elasticsearch.enabled .Values.customResource.elasticsearch.defaultAuth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elasticsearch-operator.name" . }}-elasticsearch-es-elastic-user
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: {{ template "elasticsearch-operator.name" . }}-elasticsearch
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  elastic: {{ .Values.customResource.elasticsearch.defaultAuth.password | b64enc }}
{{- end }}
