{{- if and .Values.customResource.elasticsearch.enabled .Values.customResource.elasticsearch.defaultAuth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elasticsearch-operator.name" . }}-es-elastic-user
  annotations:
    "helm.sh/hook": "pre-install"
data:
  elastic: {{ .Values.customResource.elasticsearch.defaultAuth.password | b64enc }}
{{- end }}
