rook:
  image:
    repository: rook/ceph
    tag: v1.6.7

cluster:
  image:
    repository: ceph/ceph
    tag: v15.2.13
  mon:
    # should be odd number
    count: 3
  mgr:
    # should be 1 or 2
    count: 1
  dashboard:
    enabled: true
  monitoring:
    enabled: false
  network:
    hostNetworkingEnabled: false
  # To control where various services will be scheduled by kubernetes, use the placement configuration sections below.
  # The example under 'all' would have all services scheduled on kubernetes nodes labeled with 'role=storage-node' and
  # tolerate taints with a key of 'storage-node'.
  placement: {}
#    all:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#          - matchExpressions:
#            - key: role
#              operator: In
#              values:
#              - storage-node
#      tolerations:
#      - key: storage-node
#        operator: Exists
  crashCollector:
    enabled: true
block_pools:
  - name: taco
    size: 3
    requireSafeReplicaSize: true
storageclass:
  name: rbd
  pool: taco
