apiVersion: v1
kind: Pod
metadata:
  name: psql
  namespace: fed
spec:
  containers:
  - name: psql
    image: jaesanglee/backup-postgresql:0.1.0
    command:
      - tail 
      - -f
      - /etc/hosts
