{{- if .Values.f5_ingress.enabled }}
{{- $envAll := . }}
{{- range .Values.f5_ingress.ingresses }}
---
{{- tuple  $envAll . .name .f5.ip | include "custom-network.genf5Ingress" }}

{{- if .f5.public}}
---
{{- tuple  $envAll . (printf "%v-public" .name) .f5.public  | include "custom-network.genf5Ingress" }}
{{- end}}

{{- end }}
{{- end }}
