---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "servicemesh-portal.fullname" . }}-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "servicemesh-portal.serviceAccountName" . }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io