apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servicemesh-portal.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.namespace }}  
data:
  application.yaml: {{ toYaml .Values.application | quote }}