apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicemesh-portal.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "servicemesh-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
  selector:
    {{- include "servicemesh-portal.selectorLabels" . | nindent 4 }}