{{- if .Values.objectStorage.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectStorage.secretName }}
  namespace: {{ .Release.Namespace }}
stringData:
  objstore.yml: |-
    type: {{ default "s3" .Values.objectStorage.type}}
    config:
      bucket: {{ .Values.objectStorage.bucketName }}
      endpoint: {{ .Values.objectStorage.endpoint }}
      access_key: {{ .Values.objectStorage.access_key }}
      secret_key: {{ .Values.objectStorage.secret_key }}
{{- end }}