{{- if .Values.sidecarsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sidecarsService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.sidecarsService.type }}
  ports:
    - port: {{ .Values.sidecarsService.port }}
      targetPort: http
{{- if and (eq .Values.sidecarsService.type "NodePort") .Values.sidecarsService.nodePort }}
      nodePort: {{ .Values.sidecarsService.nodePort }}
{{- end }}
      protocol: TCP
      name: grpc
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.sidecarsService.name }}
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  {{- range $idx, $ip := .Values.sidecarsService.endpoints }}
  - ip: {{ $ip }}
  {{- end }}
  ports:
    - port: {{ .Values.sidecarsService.port }}
{{- end }}
