## override Chart Name
nameOverride: taco

elasticsearchOperator:
  enabled: true

  createNamespace: true
  namespace: elastic-system

  createCustomResource: true

  rbac:
    create: true

  image:
    repository: docker.elastic.co/eck/eck-operator
    tag: 1.0.0

  resources:
    limits:
      cpu: 1
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 50Mi

customResource:
  elasticsearch:
    enabled: true

    ## admin user for Elasticsearch. Currently, unable to change user name
    defaultAuth:
      # username: elastic
      password: tacoword

    javaOpts: "-Xms256m -Xmx256m"

    ## Elasticsearch Version
    version: 7.5.1
    image: docker.elastic.co/elasticsearch/elasticsearch
    
    ## Elasticsearch instance count 
    count: 3

    ## Elasticsearch Config
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false

    ## http setting for Elasticsearch
    http:
      ports:
      - name: elasticsearch
        targetPort: 9200
        port: 9200
    #   service:
    #     spec:
    #       # expose this cluster Service with a LoadBalancer
    #       type: LoadBalancer
    #   tls:
    #     selfSignedCertificate:
    #       # add a list of SANs into the self-signed HTTP certificate
    #       subjectAltNames:
    #       - ip: 192.168.1.2
    #       - ip: 192.168.1.3
    #       - dns: elasticsearch-sample.example.com
    #     certificate:
    #       # provide your own certificate
    #       secretName: my-cert
 
    ## podTemplates
    # podTemplate:
    #   spec:
    #     volumes:
    #     - name: elasticsearch-data
    #       emptyDir: {}
    ## Storage definition for Elasticsearch instance.
    ## Must be set
    ##
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
          storageClassName: rbd
    #   selector: {}

  kibana:
    enabled: true
    version: 7.4.2
    image: docker.elastic.co/kibana/kibana
    ## container resources
    # resources:
    #   limits:
    #     cpu:
    #     memory:
    ## http setting for Kibana instance
    http:
      service:
        spec:
          type: NodePort
          ports:
          - name: kibana-dashboard-kb-http
            nodePort: 30001
            targetPort: 5601
            port: 5601
    #  tls:
    #    certificate: {}
    #    selfSignedCertificate:
    #      disabled: true

