## override Chart Name
nameOverride: taco

elasticsearchOperator:
  enabled: true

  createNamespace: true
  namespace: elastic-system

  createCustomResource: true

  rbac:
    create: true

  image:
    repository: docker.elastic.co/eck/eck-operator
    tag: 1.0.0

  resources:
    limits:
      cpu: 1
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 50Mi

customResource:
  elasticsearch:
    enabled: true

    ## admin user for Elasticsearch. Currently, unable to change user name
    defaultAuth:
      # username: elastic
      password: tacoword

    ## Elasticsearch Version
    version: 7.5.1
    image: docker.elastic.co/elasticsearch/elasticsearch
    
    ## Elasticsearch instance count 
    count: 3

    ## Elasticsearch Config
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false

    ## http setting for Elasticsearch
    # http:
    #   service:
    #     spec:
    #       # expose this cluster Service with a LoadBalancer
    #       type: LoadBalancer
    #   tls:
    #     selfSignedCertificate:
    #       # add a list of SANs into the self-signed HTTP certificate
    #       subjectAltNames:
    #       - ip: 192.168.1.2
    #       - ip: 192.168.1.3
    #       - dns: elasticsearch-sample.example.com
    #     certificate:
    #       # provide your own certificate
    #       secretName: my-cert
 
    ## Storage definition for Elasticsearch instance.
    ## Must be set
    ##
    # volumeClaimTemplates:
    # - metadata:
    #     name: elasticsearch-data
    #   spec:
    #     accessModes: ["ReadWriteOnce"]
    #     resources:
    #       requests:
    #         storage: 500Gi
    #     storageClassName: gluster
    #   selector: {}

  kibana:
    enabled: true
    version: 7.4.2
    image: docker.elastic.co/kibana/kibana
    ## http setting for Kibana instance
    # http:
    #   service:
    #     metadata:
    #       creationTimestamp: null
    #     spec:
    #       type: NodePort
    #   tls:
    #     certificate: {}
    #     selfSignedCertificate:
    #       disabled: true

