image:
  elasticsearchTemplates: 
    repository: docker.io/openstackhelm/heat
    tag: newton
    pullPolicy: IfNotPresent

## override Chart Name
nameOverride: taco

elasticsearchOperator:
  enabled: true

  namespace: elastic-system

  hyperkubeImage:
    repository: k8s.gcr.io/hyperkube
    tag: v1.15.3
    pullPolicy: IfNotPresent

  rbac:
    create: true

  image:
    repository: docker.elastic.co/eck/eck-operator
    tag: 1.1.1

  resources:
    limits:
      cpu: 1
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 50Mi

customResource:
  elasticsearch:
    enabled: true

    ## admin user for Elasticsearch. Currently, unable to change user name
    defaultAuth:
      # username: elastic
      password: tacoword

    image:
      repository: docker.elastic.co/elasticsearch/elasticsearch
      tag: 7.5.1

    ## empty {} means podDisruptionBudget disabled
    podDisruptionBudget:
      enabled: false

    ## http setting for Elasticsearch
    http:
      ports:
      - name: elasticsearch
        targetPort: 9200
        port: 9200
    #   service:
    #     spec:
    #       # expose this cluster Service with a LoadBalancer
    #       type: LoadBalancer
    #   tls:
    #     selfSignedCertificate:
    #       # add a list of SANs into the self-signed HTTP certificate
    #       subjectAltNames:
    #       - ip: 192.168.1.2
    #       - ip: 192.168.1.3
    #       - dns: elasticsearch-sample.example.com
    #     certificate:
    #       # provide your own certificate
    #       secretName: my-cert

    nodeSets:
      master:
        enabled: true
        # nodeSelector:
        #   taco-lma: enabled
        ## Elasticsearch instance count 
        count: 3
        ## Elasticsearch Config
        config:
          node.master: true
          node.data: false
          node.ingest: false
          node.store.allow_mmap: false
        ## JVM Memory config
        javaOpts: "-Xms256m -Xmx256m"
        ## Resource Max
        limitCpu: 1
        limitMem: 0.5Gi  
        ## Storage definition for Elasticsearch instance.
        ## Must be set
        ##
        pvc:
          accessModes: "ReadWriteOnce"
          storageClassName: rbd
          size: 1Gi
      hotdata: 
        enabled: true
        # nodeSelector:
        #   taco-lma: enabled
        ## Elasticsearch instance count 
        count: 3
        ## Elasticsearch Config
        config:
          node.data: true
          node.ingest: true
          node.master: false
          node.store.allow_mmap: false
          node.attr.hotwarm: hot
        javaOpts: "-Xms2g -Xmx2g"
        limitCpu: 1
        limitMem: 4Gi
        pvc:
          accessModes: "ReadWriteOnce"
          storageClassName: rbd
          size: 5Gi
      warmdata: 
        enabled: false
        # nodeSelector:
        #   taco-lma: enabled
        ## Elasticsearch instance count 
        count: 2
        ## Elasticsearch Config
        config:
          node.data: true
          node.ingest: true
          node.master: false
          node.store.allow_mmap: false
          node.attr.hotwarm: warm 
        javaOpts: "-Xms256m -Xmx256m"
        limitCpu: 1
        limitMem: 0.5Gi
        pvc:
          storageClassName: rbd
          size: 10Gi
      client: 
        enabled: true
        # nodeSelector:
        #   taco-lma: enabled
        ## Elasticsearch instance count 
        count: 1
        ## Elasticsearch Config
        config:
          node.data: false
          node.ingest: false
          node.master: false
          node.store.allow_mmap: false 
        javaOpts: "-Xms1g -Xmx1g"
        limitCpu: 1
        limitMem: 2Gi
  kibana:
    enabled: true
    image:
      repository: docker.elastic.co/kibana/kibana
      tag: 7.5.1

    limitCpu: 1
    limitMem: 2Gi
    ## container resources
    # resources:
    #   limits:
    #     cpu:
    #     memory:
    ## http setting for Kibana instance
    http:
      service:
        spec:
          type: NodePort
          ports:
          - name: kibana-dashboard-kb-http
            nodePort: 30001
            targetPort: 5601
            port: 5601
    # nodeSelector:
    #   taco-lma: enabled
    #  tls:
    #    certificate: {}
    #    selfSignedCertificate:
    #      disabled: true
