{{- $envAll := . }}
{{- if eq .Values.ingress.enabled true }}
{{- range .Values.ingress.endpoints }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- if .annotations }}
  annotations:
  {{- range $akey, $avalue := .annotations }}
    {{ $akey }}: {{ $avalue | quote }}
  {{- end }}
  {{- end }}
  name: {{ include "cloud-console.fullname" $envAll }}-{{ .name }}
spec:
  rules:
  - host: {{ .main.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "cloud-console.fullname" $envAll }}
          servicePort: {{ $envAll.Values.service.port }}
        path: /
{{- $prefix := .ccproxy.host.prefix}}
{{- $postfix := .ccproxy.host.postfix}}
{{- $from := int $envAll.Values.service.proxy_from}}
{{- $to := int (add $envAll.Values.service.proxy_to 1)}}
{{- range untilStep $from $to 1 }}
  - host: {{ $prefix }}{{ . }}{{ $postfix }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "cloud-console.fullname" $envAll }}-{{ . }}
          servicePort: {{ . }}
{{- end }}
---
{{- end }}
{{- end }}

