{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

{{- $secret := .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $release_name }}-secret"
  labels:
    helm.sh/chart: "{{ $chart_name }}-{{ $chart_version }}"
    app.kubernetes.io/name: "{{ $chart_name }}"
    app.kubernetes.io/instance: "{{ $release_name }}"
    app.kubernetes.io/version: "{{ $chart_version }}"
type: Opaque
data:
  password: {{ $secret.password | b64enc }}

