apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-metrics-app
  labels:
    service-monitor: sample-metrics-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: sample-metrics-app
  endpoints:
  - port: web

