apiVersion: v1
kind: Service
metadata:
  name: sample-metrics-app
  labels:
    app: sample-metrics-app
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: web
    port: 80
    targetPort: 8080
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: sample-metrics-app

