# Taco Registry Chart
# Registry, Postgres, Clair, Builder, App

namespace: cicd
ingressPort: 80

# Taco-Registry
tacoRegistry:
  name: taco-private-registry
  deployment:
    image: registry:2
    auth:
      service: taco-registry
      issuer: taco-registry
      keyPassword: taco-registry
      keyPairAlias: servercert
      keyPairPassword: taco-registry
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 5000
        targetPort: 5000
        nodePort:    
  ingress1:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 10240m
      virtual-server.f5.com/health: |
        [
          {
            "path":     "skb-registry.taco/",
            "send":     "HTTP GET /",
            "interval": 5,
            "timeout":  10
          }
        ]
      virtual-server.f5.com/ip: 10.10.202.15
      virtual-server.f5.com/partition: k8s-dev
    host: skb-registry.taco
    paths:
      - path: /
        port: 5000
  ingress2:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 10240m
      virtual-server.f5.com/health: |
        [
          {
            "path":     "skb-registry.taco/",
            "send":     "HTTP GET /",
            "interval": 5,
            "timeout":  10
          }
        ]
      virtual-server.f5.com/ip: 175.113.150.30
      virtual-server.f5.com/partition: k8s-dev
    host: skb-registry.taco
    paths:
      - path: /
        port: 5000
  ingressPub1:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 10240m
      virtual-server.f5.com/health: |
        [
          {
            "path":     "registry.skb-doj-dev01.btvpaas.com/",
            "send":     "HTTP GET /",
            "interval": 5,
            "timeout":  10
          }
        ]
      virtual-server.f5.com/ip: 10.10.202.15
      virtual-server.f5.com/partition: k8s-dev
    host: registry.skb-doj-dev01.btvpaas.com
    paths:
      - path: /
        port: 5000
  ingressPub2:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 10240m
      virtual-server.f5.com/health: |
        [
          {
            "path":     "registry.skb-doj-dev01.btvpaas.com/",
            "send":     "HTTP GET /",
            "interval": 5,
            "timeout":  10
          }
        ]
      virtual-server.f5.com/ip: 175.113.150.30
      virtual-server.f5.com/partition: k8s-dev
    host: registry.skb-doj-dev01.btvpaas.com
    paths:
      - path: /
        port: 5000
  volume:
    enabled: true
    storageClassName: netapp
    data:
      size: 10Gi

# Taco-db : Postgres
tacoDb:
  name: taco-db
  useExternalDb: false
  deployment:
    image: postgres:latest
    data:
      host: taco-db.default.svc
      port: 5432
      rootDb: postgres
      rootUser: postgres
      rootPassword: postgres1234
      db: registry
      user: registry
      password: registry1234
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 5432
        targetPort: 5432
        nodePort:
  volume:
    enabled: true
    storageClassName: netapp
    data:
      size: 10Gi

# Taco-clair : Clair
tacoClair:
  name: taco-clair
  deployment:
    image: quay.io/coreos/clair:latest
    replicas: 1
    hostAliases:
      - ip: "10.10.202.15"
        hostnames:
          - "skb-registry.taco"
    data:
      db: clair
      user: clair
      password: clair
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 6060
        targetPort: 6060
        nodePort:
      - name: health
        port: 6061
        targetPort: 6061
        nodePort:

# Taco-registry-builder : Builder
tacoRegistryBuilder:
  name: taco-registry-builder
  deployment:
    image: boozer83/taco-registry-builder:latest
    replicas: 1
    hostAliases:
      - ip: "10.10.202.15"
        hostnames:
        - "skb-registry.taco"
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 4000
        targetPort: 4000
        nodePort:
  volume:
    data:
      size: 100Mi
      path: /var/run/docker.sock
  mirrors:
    - ip: 175.113.150.29
      host: registry.skb-doj-stg01.btvpaas.com
      port: 80

# Taco-registry-app : App
tacoRegistryApp:
  name: taco-registry-app
  deployment:
    image: boozer83/taco-registry-app:latest
    replicas: 1
    hostAliases:
      - ip: "175.113.150.30"
        hostnames:
        - "keycloak.skb-doj-dev01.btvpaas.com"
    env:
      - name: KEYCLOAK_AUTH_SERVER_URI
        value: "https://keycloak.skb-doj-dev01.btvpaas.com/auth"
      - name: KEYCLOAK_CLIENT_ID
        value: "registry"
      - name: KEYCLOAK_REALM
        value: "nextpaas"
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 8080
        targetPort: 8080
        nodePort:
  ingress:
    annotations:
      virtual-server.f5.com/health: |
        [
          {
            "path":     "taco-registry.skb-doj-dev01.btvpaas.com/",
            "send":     "HTTP GET /",
            "interval": 5,
            "timeout":  10
          }
        ]
      virtual-server.f5.com/ip: 10.10.202.15
      virtual-server.f5.com/partition: k8s-dev
    host: taco-registry.skb-doj-dev01.btvpaas.com
    paths:
      - path: /
        port: 8080
  ingressPub:
    annotations:
      virtual-server.f5.com/health: |
        [
          {
            "path":     "taco-registry.skb-doj-dev01.btvpaas.com/",
            "send":     "HTTP GET /",
            "interval": 5,
            "timeout":  10
          }
        ]
      virtual-server.f5.com/ip: 175.113.150.30
      virtual-server.f5.com/partition: k8s-dev
    host: taco-registry.skb-doj-dev01.btvpaas.com
    paths:
      - path: /
        port: 8080
