workflowController:
  image:
    repository: argoproj/workflow-controller
    tag: v2.12.0-rc4

  executor:
    image:
      repository: argoproj/argoexec
      tag: v2.12.0-rc4

argoServer:
  image:
    repository: argoproj/argocli
    tag: v2.9.4
  
  service:
    type: NodePort
    nodePort: 30004

nodeSelector: {}

artifactRepository:
  enalbed: false
  # s3:
  #   bucket: my-bucket
  #   endpoint: minio:9000
  #   insecure: true
  #   accessKeySecret:
  #     name: my-minio-cred
  #     key: accesskey
  #   secretKeySecret:
  #     name: my-minio-cred
  #     key: secretkey

workflowArchive: 
  enabled: false
  archiveTTL: 30d

mysql:
  enabled: false
  user: argo
  database: argo
  password: dkrhpw
  persistence:
    storageClass: rbd
    accessMode: ReadWriteOnce
    size: 8Gi
  image:
    repository: mysql
    tag: 8
