workflowController:
  image:
    repository: argoproj/workflow-controller
    tag: latest

  executor:
    image:
      repository: argoproj/argoexec
      tag: latest

argoServer:
  image:
    repository: argoproj/argocli
    tag: v2.9.4

nodeSelector: {}

artifactRepository:
  enalbed: false
  # s3:
  #   bucket: my-bucket
  #   endpoint: minio:9000
  #   insecure: true
  #   accessKeySecret:
  #     name: my-minio-cred
  #     key: accesskey
  #   secretKeySecret:
  #     name: my-minio-cred
  #     key: secretkey

workflowArchive: 
  enabled: false
  archiveTTL: 30d
  mysql:
    host: argo-mysql
    port: 3306
    database: argo
    tableName: argo_workflows
    userNameSecret:
      name: argo-mysql-config
      key: username
    passwordSecret:
      name: argo-mysql-config
      key: password

mysql:
  enabled: false
  mysqlUser: argo
  mysqlDatabase: argo
  mysqlPassword: dkrhpw
  persistence:
    storageClass: rbd
    accessMode: ReadWriteOnce
    size: 8Gi
