apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prepare-etcd-secret.fullname" . }}
spec:
  template:
    metadata:
      name: {{ include "prepare-etcd-secret.fullname" . }}
    spec:
      serviceAccountName: {{ include "prepare-etcd-secret.serviceAccountName" . }}
      containers:
      - name: hyperkube
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/bash
        - -c
        - |
          kubectl create secret generic etcd-client-cert \
          --from-file=etcd-ca=/ssl/{{ .Values.etcd.certfile }} \
          --from-file=etcd-client=/ssl/{{ .Values.etcd.client_certfile }} \
          --from-file=etcd-client-key=/ssl/{{ .Values.etcd.client_keyfile }} \
          --namespace {{ .Release.Namespace }}
        volumeMounts:
        - name: ssldir
          mountPath: /ssl
      volumes:
      - name: ssldir
        hostPath:
          path: {{ .Values.etcd.certdir }}
          type: Directory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      restartPolicy: OnFailure
