{{- if and .Values.fluentbit.enabled }}
apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: v1.4.5
spec:
  image: siim/fluent-bit-for-operator:1.4.5
  positionDB:
    emptyDir: {}
  fluentBitConfigName: fluent-bit-config
  containerLogRealPath: /var/lib/docker/containers
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
  - key: node-role.kubernetes.io/node
    operator: Exists
{{- end}}