{{- if and .Values.fluentbit.enabled }}
apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: v1.4.5
spec:
  image: "{{ .Values.image.fluentbit.repository }}:{{ .Values.image.fluentbit.tag }}"
  positionDB:
    hostPath:
      path: /var/log/flb_kube.db
      type: FileOrCreate
  fluentBitConfigName: fluent-bit-config
  containerLogRealPath: /var/lib/docker/containers
{{- if and .Values.fluentbit.daemonset.spec.tolerations}}
  tolerations:
{{- range $i, $toleration :=  .Values.fluentbit.daemonset.spec.tolerations }}
  - key: {{ $toleration.key}} 
    operator: {{ $toleration.operator}} 
{{- end}}
{{- end}}
{{- if and .Values.fluentbit.daemonset.spec.resource}}
  resources: 
{{- toYaml .Values.fluentbit.daemonset.spec.resource | nindent 4}}
{{- end}}
{{- end}}