{{- if and .Values.fluentbit.enabled }}
{{- range $i, $input := .Values.fluentbit.targetLogs }}
---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: input-{{ $input.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  tail: 
    bufferChunkSize: 2M
    bufferMaxSize: 2M
    db: /fluent-bit/tail
    memBufLimit: 20MB
    parser: syslog-rfc5424
    path: {{ $input.path }}
    tag: {{ $input.tag }}
{{- end }}
{{- end }}