{{- if and .Values.fluentbit.enabled }}
apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: input-docker
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  tail: 
    bufferChunkSize: 1M
    bufferMaxSize: 1M
    db: /fluent-bit/tail
    memBufLimit: 20MB
    parser: docker
    path: /var/log/containers/*.log
    tag: kube.*
---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: input-ubuntu
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  tail: 
    bufferChunkSize: 1M
    bufferMaxSize: 1M
    db: /fluent-bit/tail
    memBufLimit: 5MB
    parser: syslog-rfc5424
    path: /var/log/syslog
    tag: syslog.*
---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: input-centos
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  tail: 
    bufferChunkSize: 1M
    bufferMaxSize: 1M
    db: /fluent-bit/tail
    memBufLimit: 5MB
    parser: syslog-rfc5424
    path: /var/log/messages
    tag: syslog.*
{{- end}}