{{- if and .Values.fluentbit.enabled .Values.fluentbit.outputs.es.enabled .Values.fluentbit.outputs.es.template.enabled }}
{{- $envAll := . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-es-template
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "fluentbit-operator.name" . }}
{{ include "fluentbit-operator.labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: {{ $.Release.Name }}-es-template
      labels:
        app: {{ template "fluentbit-operator.name" . }}
{{ include "fluentbit-operator.labels" . | indent 8 }}
    spec:
{{- if .Values.fluentbit.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fluentbit.nodeSelector | indent 8 }}
{{- end}}
      containers:
      - name: template
        image: "{{ .Values.image.elasticsearchTemplates.repository }}:{{ .Values.image.elasticsearchTemplates.tag }}"
        imagePullPolicy: "{{ .Values.image.elasticsearchTemplates.pullPolicy }}"
        env:
          - name: ES_URL
            value: https://{{.Values.fluentbit.outputs.es.host}}:{{.Values.fluentbit.outputs.es.port}}
          - name: ES_USER
            value: {{ .Values.fluentbit.outputs.es.username }}
          - name: ES_PW
            value: {{ .Values.fluentbit.outputs.es.password  }}
          - name: ELASTIC_PW
            valueFrom:
              secretKeyRef:
                name: {{ .Values.fluentbit.outputs.es.elasticPasswordSecret  }}
                key: elastic
        command:
        - /bin/sh
        - -c
        - /tmp/create_template.sh
        volumeMounts:
        - name: {{ $.Release.Name }}-cr-cm
          mountPath: /tmp/create_template.sh
          subPath: create_template.sh
          readOnly: true
        {{ range .Values.fluentbit.outputs.es.template.templates }}
        - name: {{ $.Release.Name }}-cr-cm
          mountPath: /tmp/template-{{.name}}.json
          subPath: template-{{.name}}.json
          readOnly: true
        {{ end }}
        {{ range .Values.fluentbit.outputs.es.template.ilms }}
        - name: {{ $.Release.Name }}-cr-cm
          mountPath: /tmp/ilm-{{.name}}.json
          subPath: ilm-{{.name}}.json
          readOnly: true
        {{ end }}
        {{ range .Values.fluentbit.targetLogs }}
        {{if .index}}
        - name: {{ $.Release.Name }}-cr-cm
          mountPath: /tmp/index-{{.index }}.json
          subPath: index-{{.index }}.json
          readOnly: true
          {{- range .multi_index}}
        - name: {{ $.Release.Name }}-cr-cm
          mountPath: /tmp/index-{{.index }}.json
          subPath: index-{{.index }}.json
          readOnly: true
          {{- end }}
        {{ end }}
        {{ end }}
      volumes:
      - name: {{ $.Release.Name }}-cr-cm
        configMap:
          name: {{ $.Release.Name }}-cr-cm
          defaultMode: 365
      restartPolicy: OnFailure
{{- end }}
