{{- if .Values.fluentbit.enabled }}
{{- $envAll := . }}
{{- if $envAll.Values.fluentbit.outputs.es.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fluentbit.outputs.es.username }}-es-secret
  namespace: {{ $envAll.Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.fluentbit.outputs.es.username | b64enc }}
  password: {{ .Values.fluentbit.outputs.es.password | b64enc }}
{{- range $i, $input := $envAll.Values.fluentbit.targetLogs }}
{{- if not $input.do_not_store_as_default}}
---
  {{- tuple  $envAll $input $input.index $input.tag | include "fluentbit-operator.fluentbit.output.es" }}
{{- end }}

  {{ range $input.multi_index }}
--- 
    {{- $newTag := (printf "seperate.%s.*" .index) }}
    {{- tuple  $envAll $input .index $newTag | include "fluentbit-operator.fluentbit.output.es" }}
  {{- end }}
{{- end }}

{{ if and $envAll.Values.fluentbit.outputs.http.enabled }}
---
# regex-based log exporter
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: {{ template "fluentbit-operator.fullname" $envAll }}-exporter
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "m_*"
  http:
    host: {{ template "fluentbit-operator.name" $envAll  }}-exporter.{{ $envAll.Release.Namespace }}.svc.{{ $envAll.Values.global.base_cluster_url }}
    port: 2112
    uri: "/logs"
    format: json
{{- end }}
{{- end }}
{{- if and $envAll.Values.fluentbit.outputs.kafka.enabled }}
---
# kafka support
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: {{ template "fluentbit-operator.fullname" $envAll  }}-kafka
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "kube*"
  kafka:
    brokers: {{ $envAll.Values.fluentbit.outputs.kafka.broker }}
    topics: {{ $envAll.Values.fluentbit.outputs.kafka.topic }}
    format: json
{{- end }}
{{- end }}
