{{- if and .Values.fluentbit.enabled .Values.fluentbit.alerts.enabled -}}
---
kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  annotations:
    prometheus-operator-validated: 'true'
  name: {{ template "fluentbit-operator.fullname" . }}-alert
  namespace:  {{ .Values.fluentbit.alerts.namespace }}
spec:
  groups:
    - name: log-based-alert
{{- range .Values.fluentbit.alerts.rules }}
      rules:
        - alert: log-has-{{.name}}
          annotations:
            message: >- 
              {{ .message }}
            summary: >-
              {{ .summary }}
          expr: taco_logging_system_alert == 1
          labels:
            severity: {{ .severity }}
{{- end}}
{{- end}}