{{- if .Values.conf -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    logLevel: {{ .Values.conf.logLevel }}
    logFormat: json
    route:
      routes:
      - match:
        - receiver: default
{{- range .Values.conf.default.additionalDefaultReceivers}}
        - receiver: {{ . }}
{{- end }}
{{- range $name, $route:= .Values.conf.additionalRoutes}}
    - name: {{ $name }}
      {{- toYaml $route | nindent 6}}
{{- end }}
    receivers:
    - name: "default"
      elasticsearch:
        hosts:
        {{- toYaml .Values.conf.default.hosts | nindent 8 }}
        index: {{.Values.conf.default.index }}
        username: {{.Values.conf.default.user }}
        password: {{.Values.conf.default.password }}
        tls: # optional, advanced options for tls
          insecureSkipVerify: true
{{- range $name, $receiver:= .Values.conf.additionalReceivers}}
    - name: {{ $name }}
      {{- toYaml $receiver | nindent 6}}
{{- end }}

{{- end}}