{{- range .Values.keycloakUser }}
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  user:
    username: "{{ .name }}"
    firstName: "{{ .firstName }}"
    lastName: "{{ .lastName }}"
    email: "{{ .email }}"
    enabled: True
    credentials:
      - type: "password"
        value: "{{ .password }}"
  realmSelector:
    matchLabels:
      realm: {{ .realm }}
{{- end }}
