apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
stringData:
    POSTGRES_DATABASE: "{{ .Values.keycloak.externalDatabase.databaseName }}"
    # MUST BE FQDN FOR ADDRESS
    POSTGRES_EXTERNAL_ADDRESS: "{{ .Values.keycloak.externalDatabase.address }}"
    POSTGRES_EXTERNAL_PORT: "{{ .Values.keycloak.externalDatabase.port }}"
    POSTGRES_PASSWORD: "{{ .Values.keycloak.externalDatabase.password }}"
    # Required for AWS Backup functionality
    POSTGRES_SUPERUSER: "{{ .Values.keycloak.externalDatabase.superuserEnabled }}"
    POSTGRES_USERNAME: "{{ .Values.keycloak.externalDatabase.username }}"
type: Opaque
