apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: {{ .Values.cluster_name }}-control-plane
  namespace: {{ .Values.namespace }}
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: OpenStackMachineTemplate
    name: {{ .Values.cluster_name }}-control-plane
  kubeadmConfigSpec:
    clusterConfiguration:
{{- if .Values.kube.config.apiServer }}
      apiServer:
        {{- if .Values.kube.config.apiServer.extraArgs }}
        extraArgs:
        {{- range $key, $val := .Values.kube.config.apiServer.extraArgs }}
          {{ $key }}: {{ $val }}
        {{- end }}
        {{- end }}
        {{- if .Values.kube.config.apiServer.extraVolumes }}
        extraVolumes:
        {{- range .Values.kube.config.apiServer.extraVolumes }}
        -  {{- . | toYaml | nindent 10 -}}
        {{- end }}
        {{- end }}
{{- end }}
{{- if .Values.kube.config.controllerManager }}
      controllerManager:
        {{- if .Values.kube.config.controllerManager.extraArgs }}
        extraArgs:
        {{- range $key, $val := .Values.kube.config.controllerManager.extraArgs }}
          {{ $key }}: {{ $val }}
        {{- end }}
        {{- end }}
        {{- if .Values.kube.config.controllerManager.extraVolumes }}
        extraVolumes:
        {{- range .Values.kube.config.controllerManager.extraVolumes }}
        -  {{- . | toYaml | nindent 10 -}}
        {{- end }}
        {{- end }}
{{- end }}
{{- if .Values.kube.config.scheduler }}
      scheduler:
        {{- if .Values.kube.config.scheduler.extraArgs }}
        extraArgs:
        {{- range $key, $val := .Values.kube.config.scheduler.extraArgs }}
          {{ $key }}: {{ $val }}
        {{- end }}
        {{- end }}
        {{- if .Values.kube.config.scheduler.extraVolumes }}
        extraVolumes:
        {{- range .Values.kube.config.scheduler.extraVolumes }}
        -  {{- . | toYaml | nindent 10 -}}
        {{- end }}
        {{- end }}
{{- end }}
      etcd:
        local:
          extraArgs:
            election-timeout: {{ .Values.etcd.election_timeout | quote }}
      imageRepository: k8s.gcr.io
    files:
    - content: {{ include "helm-toolkit.utils.to_ini" .Values.openstack.cloud.conf | b64enc }}
      encoding: base64
      owner: root
      path: /etc/kubernetes/cloud.conf
      permissions: "0600"
    - content: {{ .Values.openstack.cloud.cacert | b64enc }}
      encoding: base64
      owner: root
      path: /etc/certs/cacert
      permissions: "0600"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        name: {{`'{{ local_hostname }}'`}}
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        name: {{`'{{ local_hostname }}'`}}
  replicas: {{ .Values.masters.replicas }} 
  version: {{ .Values.kube.version }}
