apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Values.cluster_name }}-md-0
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      files:
      - content: {{ include "helm-toolkit.utils.to_ini" .Values.openstack.cloud.conf | b64enc }}
        encoding: base64
        owner: root
        path: /etc/kubernetes/cloud.conf
        permissions: "0600"
      - content: {{ .Values.openstack.cloud.cacert | b64enc }}
        encoding: base64
        owner: root
        path: /etc/certs/cacert
        permissions: "0600"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-config: /etc/kubernetes/cloud.conf
            cloud-provider: openstack
          name: {{`'{{ local_hostname }}'`}}
