apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: {{ .Values.cluster_name }}-md-0
  namespace: {{ .Values.namespace }}
spec:
  clusterName: {{ .Values.cluster_name }}
  replicas: {{ .Values.workers.replicas }}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: {{ .Values.cluster_name }}-md-0
      clusterName: {{ .Values.cluster_name }}
{{- if .Values.workers.failure_domain }}
      failureDomain: {{ .Values.workers.failure_domain }}
{{- end }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: OpenStackMachineTemplate
        name: {{ .Values.cluster_name }}-md-0
      version: {{ .Values.kube.version }}
