apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackCluster
metadata:
  name: {{ .Values.cluster_name }}
  namespace: {{ .Values.namespace }}
spec:
  cloudName: {{ .Values.openstack.cloud.name }}
  cloudsSecret:
    name: {{ .Values.openstack.cloud.name }}-cloud-config
    namespace:  {{ .Values.namespace }}
{{- with .Values.openstack }}
  disablePortSecurity: {{ .disable_port_security | default false }}
  dnsNameservers:
{{- range $index, $dns := .dns_name_servers }}
  - {{ $dns }}
{{- end }}
  managedAPIServerLoadBalancer: {{ .managed_apiserver_loadbalancer | default true }}
  managedSecurityGroups: {{ .managed_security_groups | default true }}
  nodeCidr: {{ .node_cidr | default "10.6.0.0/24" }} 
  useOctavia: {{ .use_octavia | default true }}
{{- if .external_network_id }}
  externalNetworkId: {{ .external_network_id }}
{{- end }}
{{- end }}
{{- if .Values.bastion.enabled }}
  bastion:
    enabled: true
    flavor: {{ .Values.bastion.flavor }}
    image: {{ .Values.bastion.image }}
    sshKeyName: {{ .Values.bastion.ssh_keyname }}
{{- end }}
